version: '3.8'

services:
  api:
    build:
      context: ./server
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_URI: ${MONGO_URI}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
    ports:
      - 4000:4000
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

  web:
    build:
      context: ./client
      target: development
    environment:
      NODE_ENV: ${NODE_ENV}
    ports:
      - 5173:5173
    depends_on:
      - api
    command: bun dev
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
