version: '3.8'

services:
  api:
    build:
      context: ./server
    container_name: backend
    restart: always
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://root:example@mongodb:27017/
      ACCESS_TOKEN_SECRET: secret123
      REFRESH_TOKEN_SECRET: secret123
    ports:
      - 4000:4000
    depends_on:
      - mongodb
    networks:
      - react-express
      - express-mongo
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

  web:
    build:
      context: ./client
      target: build
    container_name: frontend
    environment:
      VITE_NODE_ENV: development
      VITE_SERVER_URL: http://localhost:4000
    ports:
      - 5173:5173
    networks:
      - react-express
    stdin_open: true
    restart: always
    depends_on:
      - api
    command: bun dev
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules

  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - '27017:27017'
    networks:
      - express-mongo
    volumes:
      - ./server/mongo_data:/data/db

networks:
  react-express:
  express-mongo:

volumes:
  mongo_data:
